import { getNowAsync } from "@/lib/getNowAsync";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FC, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: FC<{ children: ReactNode }> = async ({ children }) => {
  const timestamp = await getNowAsync();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-slate-100 font-bold p-4">Layout: {timestamp}</div>
        <div className="pl-8">{children}</div>
      </body>
    </html>
  );
};

export default Layout;
